services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "127.0.0.1:50021:50021"
    environment:
      VV_DOWNLOAD_DICT: "true"
    restart: unless-stopped
